backend:
  name: git-gateway
  repo: lukemoderwell/lukemoderwell
  branch: writing

media_folder: static/assets
public_folder: /assets

collections:
  - name: journal
    label: Journal
    folder: journal
    create: true
    editor:
      preview: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list, add_to_top: true }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
